# Generated by Django 4.1.7 on 2023-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty_details',
            name='product',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
